package-lock.json, package.json, src/components/Error.tsx, src/components/Modal.tsx, src/components/ShowPWButton.tsx, src/components/account/AccountModal.tsx, src/components/account/EmailCheckModal.tsx, src/components/account/Login.tsx, src/components/account/Signup.tsx, src/data/accountAPI/accountAPI.ts, src/pages/SignUpPage.tsx, src/types/account.d.ts
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #86 `
=> Feature 86/signup-page

src/components/Error.tsx, src/components/account/EmailCheckModal.tsx, src/components/account/Kakao.tsx, src/pages/SignUpPage.tsx
이메일 인증부분 재전송 버튼 추가 및 전체적인 플로우 수정
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #86 `
=> refactor: 이메일 인증 수정

src/App.tsx, src/components/HeaderComponent.tsx, src/data/accountAPI/accountAPI.ts, src/hooks/useGetAccountInfo.ts, src/pages/MyPage.tsx, src/pages/ProfilePage.tsx, src/pages/SignUpPage.tsx, src/types/account.d.ts
@dudwns0921 마이페이지에서 프로필 수정페이지는 아직 미완성되었고, 우선 마이페이지 상단이 조금이라도 되어야 공고부분이 진행 될 것 같아서 먼저 pr올립니다~
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
=> feat: 마이페이지 초안

package-lock.json, package.json, src/components/HeaderComponent.tsx, src/components/Loading.tsx, src/components/account/Google.tsx, src/components/account/Kakao.tsx, src/components/account/PasswordChangeModal.tsx, src/data/accountAPI/accountAPI.ts, src/pages/MyPage.tsx, src/pages/ProfilePage.tsx, src/types/account.d.ts, vite.config.ts
로그인 후 헤더부분과 
마이페이지=> 기본정보 수정 부분에서 프로필 사진, 연락가능 시간 셀렉버튼으로 구현하는 것을 제외하고는 퍼블리싱 완성했습니다.
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #92 `
=> feat: 마이페이지 기본정보 수정 1차 퍼블리싱

src/components/HeaderComponent.tsx, src/components/account/Login.tsx, src/data/accountAPI/accountAPI.ts, src/hooks/useEditAccountInfo.ts, src/hooks/useEditPassword.ts, src/hooks/useGetAccountInfo.ts, src/hooks/usePostEmailAuth.ts, src/hooks/usePostEmailCheck.ts, src/hooks/usePostLogIn.ts, src/hooks/usePostLogOut.ts, src/hooks/usePostPasswordCheck.ts, src/hooks/usePostSignUp.ts, src/pages/MyPage.tsx, src/pages/ProfilePage.tsx, src/pages/SignUpPage.tsx, src/types/account.d.ts
프로필 이미지 변경
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #92 `
=> Feature 92/my page profile part

src/pages/ProfilePage.tsx
기본정보 수정 페이지 하단에  있는 연락가능 시간대 입력방법에 이슈가 있어서 수정 후 기존 주석 처리 부분 삭제했습니다. 
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #92 `
=> refactor: 프로필 페이지 주석부분 삭제

index.html, src/components/HeaderComponent.tsx, src/components/PeopleNumSelectComponent.tsx, src/components/TechListSelectComponent.tsx, src/components/account/Login.tsx, src/components/account/Signup.tsx, src/components/common/PlaceHolderComponent.tsx, src/data/postAPI/postAPI.ts, src/hooks/useGetPostForUpdate.ts, src/lib/constants.ts, src/pages/Post/PostPage.tsx, src/styles/global.ts, src/styles/mui/custom.ts
공고 작성 페이지 기획 및 디자인 이슈 수정
- 피그마 디자인대로 재구현
- toast editor 색상 수정
추가 작업
- 이미지 경로 오류 수정
- 글쓰기 버튼 수정
closes #111
=> 공고 작성 페이지 - 기획 및 디자인 이슈 수정

src/components/Modal.tsx, src/hooks/usePostLogIn.ts
accountId 로컬스토리지에 저장 
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> feat: accountId 로컬스토리지에 저장

src/components/AccountButton.tsx, src/components/Error.tsx, src/components/HeaderComponent.tsx, src/components/Modal.tsx, src/components/ShowPWButton.tsx, src/components/account/AccountModal.tsx, src/components/account/Login.tsx, src/components/account/Signup.tsx, src/pages/MainPage.tsx, src/pages/Post/PostPage.tsx, src/pages/SignUpPage.tsx, src/styles/global.ts
우선은 로그인/회원가입 모달창과 회원가입 페이지 모바일 버전 구현 했습니다.
헤더부분과 마이페이지 기본 정보 수정 페이지는 추후에 진행하도록 하겠습니다.
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #113 `
=> feat: 로그인/회원가입 모바일 버전

.env.production
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> refactor: 소셜로그인 주소 변경

src/components/Modal.tsx, src/components/account/AccountModal.tsx, src/components/account/Login.tsx, src/components/account/Signup.tsx
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> refactor: 로그인/회원가입 모달창 디자인 수정

index.html, src/components/AccountButton.tsx, src/components/HeaderComponent.tsx, src/components/ShowPWButton.tsx, src/components/account/AccountModal.tsx, src/components/account/Kakao.tsx, src/pages/MyPage.tsx, src/pages/ProfilePage.tsx
마이페이지에서 공고부분을 제외하고 모바일 버전 구현했습니다!
*현재 메인페이지에서 공고부분이 모바일 버전이 없어서 모바일 버전 모달창이 뷰포트 기준으로 너무 넓어져서 일단은 display:none 속성을 넣어놓았습니다!
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #124 `
=> feat: 마이페이지/기본정보 수정 모바일 버전

index.html, package-lock.json, src/components/account/Kakao.tsx, vite.config.ts
기존 경서님께서 웹소켓관련 설정 추가하신 부분이 예전 서버 주소여서 그런지 소셜로그인과 충돌이 있는 것 같습니다~
그래서 일단 삭제하고 진행하겠습니다!
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> fix: 소셜로그인 에러 수정

src/hooks/usePostById.ts
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> fix: 포스트 컴포넌트 들어갔다 뒤로갔다 다른거 들어가면 API 호출하지 않아서 수정함

index.html, package.json, src/components/account/Kakao.tsx
소셜로그인 에러있었던 부분 환경 재설정 했습니다.
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #135 `
=> fix: 소셜로그인 환경 재설정

.env.production, vite.config.ts
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> .env 채팅 엔드포인트 추가

src/components/chat/MessageItem.tsx, src/components/chat/MessageRoom.tsx
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> 페치데이더 존재확인 추가

package-lock.json, package.json, src/hooks/usePostApplyment.ts
기존 사용하던 react-query 라이브러리를 usePostApplyment 훅에서 여전히 불러오고 있어서 @tanstack/react-query 라이브러리로 수정했습니다.
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #146 `
=> fix: 디테일 페이지 이슈 수정

.env.production, src/components/BannerComponent.tsx, src/components/TabComponent.tsx, src/data/accountAPI/accountAPI.ts, src/data/postAPI/postAPI.ts, src/hooks/useGetPosts.ts, src/hooks/usePostApplyment.ts, src/lib/constants.ts, src/pages/MyPage.tsx, src/styles/global.ts, src/styles/swiper.css
마이페이지 개발을 완료했습니다.
추가로 이전에 디자인팀에서 요청한 수정사항을 배너에 적용했습니다.
closes #145
=> 마이페이지 개발 및 배너 수정

.env.production, package-lock.json, src/components/HeaderComponent.tsx, src/components/chat/ChatCloseModal.tsx, src/components/chat/MessageItem.tsx, src/components/chat/MessageRoom.tsx, src/components/chat/ThereIsContent.tsx, src/components/chat/emoji.tsx, src/components/sse/eventSource.tsx, src/pages/ChatPage.tsx, src/styles/global.ts
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> Feature 122/chat page desktop UI

src/pages/ChatPage.tsx
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #14`
=> Fix: 읽지 않은 메세지 노출 되게 변경

src/components/ApplyModal.tsx, src/components/HeaderComponent.tsx, src/components/account/Google.tsx, src/components/account/Kakao.tsx, src/components/chat/MessageRoom.tsx, src/components/sse/eventSource.tsx, src/data/interceptor.ts, src/hooks/useGetAccountInfo.ts, src/hooks/usePostLogIn.ts, src/pages/ChatPage.tsx, src/pages/Post/PostDetailPage.tsx
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #157 `
=> fix: 토큰 만료시 토큰 삭제

src/pages/ProfilePage.tsx
프로필페이지 간단소개 글자길이 수정
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
`fixes #161 `
=> refactor: 간단소개 글자길이 수정
